name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (latest version)
        uses: actions/setup-node@v3
        with:
          node-version: 'node'  # Latest version of Node.js automatically

      - name: Install dependencies
        run: npm install --legacy-peer-deps  # Avoids peer dependency errors

      - name: Build project
        run: npm run build

      - name: Run tests (optional)
        run: npm test
