name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'node'  # This will automatically use the latest version of Node.js

      - name: Install dependencies
        run: npm install --legacy-peer-deps  # Avoids peer dependency errors

      - name: Run development server (dev script)
        run: npm run dev  # This will run `nodemon server.js` for development

      # Optional step: If you want to test, add test step here (if you have test scripts)
      # - name: Run tests
      #   run: npm test
